// Builds src/cvars.gen.json from mastercomfig's TF2 cvar dumps.
// Run: node tools/build-corpus.mjs
// Format per line: `name : default-or-cmd : , "flags" : help text`
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const SOURCES = [
  "https://raw.githubusercontent.com/mastercomfig/mastercomfig/release/docs/tf2/cvarlist_win.md",
  "https://raw.githubusercontent.com/mastercomfig/mastercomfig/release/docs/tf2/hiddencvars.md",
];

const LINE_RE = /^([A-Za-z_][\w-]*)\s+:\s(.*?)\s*:\s*(.*?)\s*:\s?(.*)$/;

const corpus = {};
for (const url of SOURCES) {
  const res = await fetch(url);
  if (!res.ok) {
    console.error(`FAILED ${res.status} ${url}`);
    process.exitCode = 1;
    continue;
  }
  const text = await res.text();
  let count = 0;
  for (const rawLine of text.split("\n")) {
    const m = rawLine.match(LINE_RE);
    if (!m) continue;
    const [, name, def, flagsRaw, help] = m;
    const flags = [...flagsRaw.matchAll(/"([^"]+)"/g)].map((f) => f[1]);
    const isCmd = def.trim() === "cmd";
    corpus[name.toLowerCase()] = {
      c: isCmd ? 1 : 0,
      d: isCmd ? undefined : def.trim(),
      f: flags.length ? flags : undefined,
      h: help.trim() || undefined,
    };
    count++;
  }
  console.log(`${url.split("/").pop()}: ${count} entries`);
}

const out = join(dirname(fileURLToPath(import.meta.url)), "..", "src", "cvars.gen.ts");
await mkdir(dirname(out), { recursive: true });
await writeFile(
  out,
  `// Generated by tools/build-corpus.mjs — do not edit.\nexport default ${JSON.stringify(corpus)} as Record<string, { c: 0 | 1; d?: string; f?: string[]; h?: string }>;\n`,
);
console.log(`wrote ${out} (${Object.keys(corpus).length} total)`);
