// Builds src/cvars.gen.ts from mastercomfig's TF2 cvar dumps.
// Run: node tools/build-corpus.mjs   (needs Node >= 22.6 and network access)
// Source format per line: `name : default-or-cmd : , "flags" : help text`
//
// The output is piped through biome so a regenerated corpus matches the
// committed file byte-for-byte in style. biome.json excludes `**/*.gen.ts`
// from `pnpm check`, so nothing else would ever format it.
import { spawnSync } from "node:child_process";
import { mkdir, writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const SOURCES = [
  "https://raw.githubusercontent.com/mastercomfig/mastercomfig/release/docs/tf2/cvarlist_win.md",
  "https://raw.githubusercontent.com/mastercomfig/mastercomfig/release/docs/tf2/hiddencvars.md",
];

const LINE_RE = /^([A-Za-z_][\w-]*)\s+:\s(.*?)\s*:\s*(.*?)\s*:\s?(.*)$/;

const corpus = {};
for (const url of SOURCES) {
  const res = await fetch(url);
  if (!res.ok) {
    console.error(`FAILED ${res.status} ${url}`);
    process.exitCode = 1;
    continue;
  }
  const text = await res.text();
  let count = 0;
  for (const rawLine of text.split("\n")) {
    const m = rawLine.match(LINE_RE);
    if (!m) continue;
    const [, name, def, flagsRaw, help] = m;
    const flags = [...flagsRaw.matchAll(/"([^"]+)"/g)].map((f) => f[1]);
    const isCmd = def.trim() === "cmd";
    corpus[name.toLowerCase()] = {
      c: isCmd ? 1 : 0,
      d: isCmd ? undefined : def.trim(),
      f: flags.length ? flags : undefined,
      h: help.trim() || undefined,
    };
    count++;
  }
  console.log(`${url.split("/").pop()}: ${count} entries`);
}

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, "..", "src", "cvars.gen.ts");
const source = `// Generated by tools/build-corpus.mjs — do not edit.\nexport default ${JSON.stringify(corpus)} as Record<string, { c: 0 | 1; d?: string; f?: string[]; h?: string }>;\n`;

/** Formats `text` with the repo's biome, or returns it unchanged if that fails. */
function biomeFormat(text) {
  let bin;
  try {
    bin = createRequire(import.meta.url).resolve("@biomejs/biome/bin/biome");
  } catch {
    console.warn("biome not installed — writing unformatted output");
    return text;
  }
  const run = spawnSync(process.execPath, [bin, "format", "--stdin-file-path=cvars.gen.ts"], {
    cwd: here,
    input: text,
    encoding: "utf8",
    maxBuffer: 64 * 1024 * 1024,
  });
  if (run.status !== 0 || !run.stdout) {
    console.warn(`biome format failed (${run.status}) — writing unformatted output`);
    if (run.stderr) console.warn(run.stderr.trim());
    return text;
  }
  return run.stdout;
}

await mkdir(dirname(out), { recursive: true });
await writeFile(out, biomeFormat(source));
console.log(`wrote ${out} (${Object.keys(corpus).length} total)`);
