// Builds src/cvars.gen.ts from mastercomfig's TF2 cvar dumps.
// Run: node tools/build-corpus.mjs   (needs Node >= 22.6 and network access)
// Source format per line: `name : default-or-cmd : , "flags" : help text`
//
// The dumps are `docs/tf2/cvarlist_win.md` and `docs/tf2/hiddencvars.md` in
// mastercomfig/mastercomfig (MIT) — themselves captures of Valve's own
// `cvarlist` console output. REF pins the commit they are read from so a
// rebuild is reproducible; bump it deliberately when refreshing the corpus.
//
// The output is piped through biome so a regenerated corpus matches the
// committed file byte-for-byte in style. biome.json excludes `**/*.gen.ts`
// from `pnpm check`, so nothing else would ever format it.
import { spawnSync } from "node:child_process";
import { mkdir, writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const REPO = "mastercomfig/mastercomfig";
/** Head of the `release` branch as of 2026-07-05 — the commit the committed corpus was built from. */
const REF = "c7b52734b252bb521cd22e8243bca6f81dd3ab41";
const SOURCE_PATHS = ["docs/tf2/cvarlist_win.md", "docs/tf2/hiddencvars.md"];
const SOURCES = SOURCE_PATHS.map(
  (path) => `https://raw.githubusercontent.com/${REPO}/${REF}/${path}`,
);

const HEADER = [
  "// Generated by tools/build-corpus.mjs — do not edit.",
  "//",
  `// Source: ${REPO} @ ${REF} (branch \`release\`, head as of 2026-07-05)`,
  ...SOURCES.map((url) => `//   ${url}`),
  "// Both files are dumps of Valve's own `cvarlist` console output.",
  "// Copyright (c) mastercomfig contributors, MIT",
].join("\n");

const LINE_RE = /^([A-Za-z_][\w-]*)\s+:\s(.*?)\s*:\s*(.*?)\s*:\s?(.*)$/;

const corpus = {};
for (const url of SOURCES) {
  const res = await fetch(url);
  if (!res.ok) {
    console.error(`FAILED ${res.status} ${url}`);
    process.exitCode = 1;
    continue;
  }
  const text = await res.text();
  let count = 0;
  for (const rawLine of text.split("\n")) {
    const m = rawLine.match(LINE_RE);
    if (!m) continue;
    const [, name, def, flagsRaw, help] = m;
    const flags = [...flagsRaw.matchAll(/"([^"]+)"/g)].map((f) => f[1]);
    const isCmd = def.trim() === "cmd";
    corpus[name.toLowerCase()] = {
      c: isCmd ? 1 : 0,
      d: isCmd ? undefined : def.trim(),
      f: flags.length ? flags : undefined,
      h: help.trim() || undefined,
    };
    count++;
  }
  console.log(`${url.split("/").pop()}: ${count} entries`);
}

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, "..", "src", "cvars.gen.ts");
const source = `${HEADER}\nexport default ${JSON.stringify(corpus)} as Record<string, { c: 0 | 1; d?: string; f?: string[]; h?: string }>;\n`;

/** Formats `text` with the repo's biome, or returns it unchanged if that fails. */
function biomeFormat(text) {
  let bin;
  try {
    bin = createRequire(import.meta.url).resolve("@biomejs/biome/bin/biome");
  } catch {
    console.warn("biome not installed — writing unformatted output");
    return text;
  }
  const run = spawnSync(process.execPath, [bin, "format", "--stdin-file-path=cvars.gen.ts"], {
    cwd: here,
    input: text,
    encoding: "utf8",
    maxBuffer: 64 * 1024 * 1024,
  });
  if (run.status !== 0 || !run.stdout) {
    console.warn(`biome format failed (${run.status}) — writing unformatted output`);
    if (run.stderr) console.warn(run.stderr.trim());
    return text;
  }
  return run.stdout;
}

await mkdir(dirname(out), { recursive: true });
await writeFile(out, biomeFormat(source));
console.log(`wrote ${out} (${Object.keys(corpus).length} total)`);
