// Community crosshair catalog — the Venom Crosshairs pack, pinned to
// hbivnm/Venom-Crosshairs-List commit 2e7036cd (fetched on demand, cached
// locally, installed verbatim into the execs crosshair pack).
// Generated from the repo file list; the 3 animated crossanim_* entries
// (256px multi-frame, proxy VMTs) are excluded.

export type CommunityCrosshairEntry = {
  /** Lowercased pack name execs uses (valid crosshair name). */
  id: string;
  /** Exact upstream file stem (case matters for the download URL). */
  file: string;
};

export const COMMUNITY_CROSSHAIR_CREDIT =
  "Community crosshair pack: Venom Crosshairs (HbiVnm) and the TF2 community crosshair authors (0mger, tob, lapi, bomo, ktwings, ceno, and more).";

export const COMMUNITY_CROSSHAIRS: CommunityCrosshairEntry[] = [
  { id: "bigchair1", file: "bigchair1" },
  { id: "bigcross", file: "bigcross" },
  { id: "bigcrosshair7", file: "bigcrosshair7" },
  { id: "bigcrosshair7ol", file: "bigcrosshair7OL" },
  { id: "bighair1", file: "bighair1" },
  { id: "bomo1", file: "bomo1" },
  { id: "bomo2", file: "bomo2" },
  { id: "bomo3", file: "bomo3" },
  { id: "bomo3w", file: "bomo3w" },
  { id: "bomo4", file: "bomo4" },
  { id: "bomo5", file: "bomo5" },
  { id: "bomo5ol", file: "bomo5OL" },
  { id: "bomo6", file: "bomo6" },
  { id: "bomo7", file: "bomo7" },
  { id: "bomoseeker", file: "bomoseeker" },
  { id: "brackets", file: "brackets" },
  { id: "ceno_realscout", file: "ceno_REALscout" },
  { id: "chevron", file: "chevron" },
  { id: "chevron_outline", file: "chevron_outline" },
  { id: "circle", file: "circle" },
  { id: "circledot", file: "circledot" },
  { id: "cpma_11", file: "cpma_11" },
  { id: "cpma_12", file: "cpma_12" },
  { id: "cpma_13", file: "cpma_13" },
  { id: "cpma_14", file: "cpma_14" },
  { id: "cpma_15", file: "cpma_15" },
  { id: "cpma_16", file: "cpma_16" },
  { id: "cpma_17", file: "cpma_17" },
  { id: "cpma_18", file: "cpma_18" },
  { id: "cpma_19", file: "cpma_19" },
  { id: "crossdot", file: "crossdot" },
  { id: "crosshair1", file: "crosshair1" },
  { id: "crosshair1ol", file: "crosshair1OL" },
  { id: "crosshair2", file: "crosshair2" },
  { id: "crosshair2ol", file: "crosshair2OL" },
  { id: "crosshair3", file: "crosshair3" },
  { id: "crosshair3ol", file: "crosshair3OL" },
  { id: "crosshair5", file: "crosshair5" },
  { id: "crosshair5circle", file: "crosshair5circle" },
  { id: "crosshair5circleol", file: "crosshair5circleOL" },
  { id: "crosshair5ol", file: "crosshair5OL" },
  { id: "crosshair6", file: "crosshair6" },
  { id: "crosshair6circle", file: "crosshair6circle" },
  { id: "crosshair6circleol", file: "crosshair6circleOL" },
  { id: "crosshair6ol", file: "crosshair6OL" },
  { id: "crosshair7", file: "crosshair7" },
  { id: "crosshair7circle", file: "crosshair7circle" },
  { id: "crosshair7circleol", file: "crosshair7circleOL" },
  { id: "crosshair7ol", file: "crosshair7OL" },
  { id: "crosshair7short", file: "crosshair7short" },
  { id: "crosshole1", file: "crosshole1" },
  { id: "crossholesmall1", file: "crossholesmall1" },
  { id: "crotchair1", file: "crotchair1" },
  { id: "csgo", file: "csgo" },
  { id: "csgo_gradient", file: "csgo_gradient" },
  { id: "csgo_shadow", file: "csgo_shadow" },
  { id: "despair1", file: "despair1" },
  { id: "diabotical_closed", file: "diabotical_closed" },
  { id: "diabotical_open", file: "diabotical_open" },
  { id: "dot", file: "dot" },
  { id: "dot_dolphinrider_smalleroutercircle", file: "dot_dolphinrider_smalleroutercircle" },
  { id: "eggseeker", file: "eggseeker" },
  { id: "fatcross", file: "fatcross" },
  { id: "fatcrosscircle", file: "fatcrosscircle" },
  { id: "fatcrosscircleol", file: "fatcrosscircleOL" },
  { id: "fatcrossol", file: "fatcrossOL" },
  { id: "g0r3bat", file: "g0R3bat" },
  { id: "g0r3cross", file: "g0R3cross" },
  { id: "g0r3fang", file: "g0R3fang" },
  { id: "g0r3wings", file: "g0R3wings" },
  { id: "habibcross", file: "habibCross" },
  { id: "heart2", file: "heart2" },
  { id: "highfive", file: "highfive" },
  { id: "konr_dot", file: "konr_dot" },
  { id: "kosei", file: "kosei" },
  { id: "kovaaks_bigplus", file: "kovaaks_bigplus" },
  { id: "kovaaks_emptyplus", file: "kovaaks_emptyplus" },
  { id: "kovaaks_hash", file: "kovaaks_hash" },
  { id: "kovaaks_plus", file: "kovaaks_plus" },
  { id: "kovaaks_plusdot", file: "kovaaks_plusdot" },
  { id: "ktwings", file: "ktwings" },
  { id: "ktwings_medic", file: "ktwings_medic" },
  { id: "ktwings_og", file: "ktwings_OG" },
  { id: "ktwings_solly", file: "ktwings_solly" },
  { id: "lapidarkshadowcross", file: "lapiDarkShadowCross" },
  { id: "lapidarkshadowdot", file: "lapiDarkShadowDot" },
  { id: "lapiheavycrosshair", file: "lapiHeavyCrosshair" },
  { id: "lapihole", file: "lapiHole" },
  { id: "lapiseeker", file: "lapiSeeker" },
  { id: "lapishortstop", file: "lapiShortstop" },
  { id: "lapismalldarkshadowcross", file: "lapiSmallDarkShadowCross" },
  { id: "lapitarget", file: "lapiTarget" },
  { id: "mediccross", file: "mediccross" },
  { id: "mediccrossbig", file: "mediccrossbig" },
  { id: "none", file: "None" },
  { id: "nubbicrossol", file: "nubbicrossOL" },
  { id: "omga", file: "omga" },
  { id: "omge", file: "omge" },
  { id: "opencross", file: "opencross" },
  { id: "opencrossol", file: "opencrossOL" },
  { id: "prodg_diamond", file: "prodg_diamond" },
  { id: "prodg_diamond_brackets", file: "prodg_diamond_brackets" },
  { id: "prodg_diamond_dot", file: "prodg_diamond_dot" },
  { id: "prodg_diamond_dot_small", file: "prodg_diamond_dot_small" },
  { id: "prodg_diamond_offcenter", file: "prodg_diamond_offcenter" },
  { id: "prodg_diamond_quartered", file: "prodg_diamond_quartered" },
  { id: "prodg_mediccross_sharp", file: "prodg_mediccross_sharp" },
  { id: "ql_1", file: "ql_1" },
  { id: "ql_10", file: "ql_10" },
  { id: "ql_11", file: "ql_11" },
  { id: "ql_12", file: "ql_12" },
  { id: "ql_13", file: "ql_13" },
  { id: "ql_14", file: "ql_14" },
  { id: "ql_15", file: "ql_15" },
  { id: "ql_16", file: "ql_16" },
  { id: "ql_17", file: "ql_17" },
  { id: "ql_18", file: "ql_18" },
  { id: "ql_19", file: "ql_19" },
  { id: "ql_2", file: "ql_2" },
  { id: "ql_3", file: "ql_3" },
  { id: "ql_4", file: "ql_4" },
  { id: "ql_5", file: "ql_5" },
  { id: "ql_7", file: "ql_7" },
  { id: "ql_8", file: "ql_8" },
  { id: "ql_9", file: "ql_9" },
  { id: "quarteredcircle", file: "quarteredcircle" },
  { id: "rays", file: "rays" },
  { id: "rays_shadow", file: "rays_shadow" },
  { id: "seeker", file: "seeker" },
  { id: "seekerol", file: "seekerOL" },
  { id: "seekeroldot", file: "seekerOLdot" },
  { id: "seekeroldotthicker", file: "seekerOLdotthicker" },
  { id: "seekerolsmallerthicker", file: "seekerOLsmallerthicker" },
  { id: "seekersmall_dropshadow", file: "seekersmall_dropshadow" },
  { id: "smallcrosshair7", file: "smallcrosshair7" },
  { id: "smallcrosshair7circle", file: "smallcrosshair7circle" },
  { id: "smallcrosshair7circleol", file: "smallcrosshair7circleOL" },
  { id: "smallcrosshair7ol", file: "smallcrosshair7OL" },
  { id: "sniper", file: "sniper" },
  { id: "sniperbig", file: "sniperbig" },
  { id: "sniperbigol", file: "sniperbigOL" },
  { id: "snipercircle", file: "snipercircle" },
  { id: "snipercircleol", file: "snipercircleOL" },
  { id: "sniperol", file: "sniperOL" },
  { id: "tealdot", file: "tealdot" },
  { id: "tealdotbig", file: "tealdotbig" },
  { id: "thalashseeker", file: "thalashseeker" },
  { id: "tob_ams", file: "tob_AMS" },
  { id: "tob_miniseeker", file: "tob_miniSeeker" },
  { id: "tob_miniseekerol", file: "tob_miniSeekerOL" },
  { id: "tob_ql2_big", file: "tob_ql2_big" },
  { id: "tob_ql3_smallgap", file: "tob_ql3_smallgap" },
  { id: "tob_ql3_thick", file: "tob_ql3_thick" },
  { id: "tob_rocketcross", file: "tob_rocketcross" },
  { id: "tob_seeker", file: "tob_seeker" },
  { id: "tob_wingscross", file: "tob_wingscross" },
  { id: "tob_wingscross_thick", file: "tob_wingscross_thick" },
  { id: "tob_wingsdot", file: "tob_wingsdot" },
  { id: "tob_yz", file: "tob_YZ" },
  { id: "ut2k4_shock", file: "ut2k4_shock" },
  { id: "ut2k4_shock_shadow", file: "ut2k4_shock_shadow" },
  { id: "ut2k4_shock_short", file: "ut2k4_shock_short" },
  { id: "ut99_1", file: "ut99_1" },
  { id: "wings", file: "wings" },
  { id: "wingsdot", file: "wingsdot" },
  { id: "xhairshadowdefault", file: "xhairshadowdefault" },
  { id: "xhairshadowdots", file: "xhairshadowdots" },
  { id: "xhairshadowplus", file: "xhairshadowplus" },
  { id: "xhairshadowpluss", file: "xhairshadowpluss" },
  { id: "xhairshadowrocketsthick", file: "xhairshadowrocketsthick" },
  { id: "yzdefault", file: "yzdefault" },
  { id: "yzwings", file: "yzwings" },
  { id: "zeeq_plus", file: "zeeq_plus" },
];

export function searchCommunityCrosshairs(query: string): CommunityCrosshairEntry[] {
  const needle = query.trim().toLowerCase();
  if (!needle) {
    return COMMUNITY_CROSSHAIRS;
  }
  return COMMUNITY_CROSSHAIRS.filter((entry) => entry.id.includes(needle));
}
