# Link the MSVC C runtime statically so the app starts on machines without the
# Visual C++ Redistributable (the NSIS installer does not install it).
[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]
